"""
A module for generating data for a postmodern essay generator.
This module includes lists of philosophers, concepts, terms, contexts,
adjectives, and academic vocabulary relevant to postmodern philosophy.
It also includes a dictionary of philosopher concepts,
which maps philosophers to their key concepts.
"""

import random

# Lists of philosophers
philosophers = [
    "Jean Baudrillard", "Michel Foucault", "Jacques Derrida", "Gilles Deleuze", "Félix Guattari",
    "Judith Butler", "Donna Haraway", "Fredric Jameson", "Jean-François Lyotard", "Slavoj Žižek",
    "Julia Kristeva", "Linda Hutcheon", "Brian McHale", "Paul Virilio", "Homi K. Bhabha", "Gayatri Chakravorty Spivak", "Edward Said",
    "Luce Irigaray", "Jacques Lacan", "Henri Lefebvre", "Maurice Blanchot", "Roland Barthes",
    "Richard Rorty", "Stanley Fish", "Terry Eagleton", "Brian Massumi", "Mark Fisher",
    "Franco Berardi", "Nick Land", "Manuel DeLanda", "Rosi Braidotti", "Katherine Hayles",
    "Jean-Luc Nancy", "Giorgio Agamben", "Alain Badiou", "Bruno Latour", "Isabelle Stengers",
    "Avital Ronell", "Catherine Malabou", "Quentin Meillassoux", "Ray Brassier", "Graham Harman",
    "Elizabeth Grosz", "Achille Mbembe", "Byung-Chul Han", "Bernard Stiegler", "Lauren Berlant",
    "Wang Hui", "Dipesh Chakrabarty", "Walter Mignolo", "Sylvia Wynter", "Frantz Fanon",
    "Bell Hooks", "Cornel West", "Angela Davis", "Audre Lorde", "Sara Ahmed",
    "Gayle Rubin", "Eve Kosofsky Sedgwick", "Michael Hardt", "Antonio Negri", "Étienne Balibar",
    "Ernesto Laclau", "Chantal Mouffe", "Nancy Fraser", "Axel Honneth", "Jürgen Habermas",
    "Kwame Anthony Appiah", "Martha Nussbaum", "Amartya Sen", "Arjun Appadurai", "Stuart Hall",
    "Paul Gilroy", "Édouard Glissant", "Ngũgĩ wa Thiong'o", "Chinua Achebe", "Wole Soyinka",
    "Amin Maalouf", "Tariq Ali", "Vandana Shiva", "Ashis Nandy", "Partha Chatterjee",
    "Mahmood Mamdani", "Enrique Dussel", "Anibal Quijano", "Maria Lugones", "Gloria Anzaldúa",
    "Chela Sandoval", "Linda Tuhiwai Smith", "Taiaiake Alfred", "Leanne Betasamosake Simpson", "Vine Deloria Jr."
]

# Concepts: Specific ideas or theories, often tied to philosophers or postmodernist thought
concepts = [
    "abolition", "accelerationism", "actor-network theory", "affect theory", "assemblage",
    "biopower", "biopolitics", "border thinking", "capitalocene", "care work", "chthulucene",
    "cognitive capitalism", "cognitive mapping", "coloniality of power", "control society",
    "counter-hegemony", "cultural criticism", "cultural imperialism", "cyborg",
    "data colonialism", "death of the author", "decoloniality", "decolonization",
    "deconstruction", "dependency theory", "desert of the real", "deterritorialization",
    "différance", "digital humanities", "discipline", "dromology", "ecocriticism",
    "emotional labor", "epistemic disobedience", "event", "faciality", "financialization",
    "gender performativity", "genealogy", "gig economy", "governmentality", "hauntology",
    "heterotopia", "human capital", "hybridity", "hyperreality", "immaterial labor",
    "incredulity towards metanarratives", "intersectionality", "jouissance", "land back",
    "late capitalism", "lines of flight", "minor literature", "multitude", "necropolitics",
    "neoliberal subjectivity", "neoliberalism", "new historicism", "nomadology",
    "non-philosophy", "object-oriented ontology", "orientalism", "pastiche", "phallogocentrism",
    "platform capitalism", "pluriverse", "post-truth", "posthumanism", "postmodern sublime",
    "postmodernism", "power/knowledge", "precarity", "racial capitalism", "reparations",
    "reterritorialization", "rhizome", "schizoanalysis", "self-care", "semiocapitalism",
    "settler colonialism", "simulacra", "simulacrum", "smooth space", "social reproduction theory",
    "spectacle", "speculative realism", "striated space", "subaltern", "surveillance capitalism",
    "the Anthropocene", "the commons", "the gaze", "the Other", "transnationalism",
    "war machine"
]

# Non-Italicized Terms: General terms used in postmodernist discourse, not specific to a single concept or philosopher, left non-italicized
non_italicized_terms = [
    "affect", "alterity", "anthropocene", "aporia", "archéologie", "becoming", "binary opposition",
    "body without organs", "bricolage", "burnout", "cultural logic", "cultural relativism",
    "cyberculture", "debt", "decentering", "diaspora", "digital age", "discourse", "épistème",
    "fragmentation", "global South", "globalization", "hegemony", "hypertext", "ideology",
    "immanence", "indigeneity", "intertextuality", "irony", "logocentrism", "mental health",
    "metanarrative", "mestiza consciousness", "nomadism", "panopticism", "parody", "performativity",
    "phallocentrism", "pluralism", "post-humanism", "postcolony", "poststructuralism",
    "provincializing Europe", "queer theory", "reader-response theory", "recognition",
    "refusal of work", "resilience", "schizophrenia", "sovereignty", "speed", "subjectivity",
    "subalternity", "supplement", "trace", "transgression", "transversality", "trauma",
    "wellness", "world-systems theory"
]

# Italicized Terms: Terms to be italicized when rendered
italicized_terms = [
    "aporia", "archéologie", "assemblage", "becoming", "biopower", "body without organs",
    "border thinking", "bricolage", "chthulucene", "coloniality of power", "derritorialization",
    "différance", "dromology", "épistème", "epistemic disobedience", "faciality",
    "governmentality", "hauntology", "heterotopia", "immanence", "jouissance",
    "land back", "lines of flight", "minor literature", "nomadology", "orientalism",
    "pastiche", "phallogocentrism", "pluriverse", "postmodern sublime", "reterritorialization",
    "rhizome", "schizoanalysis", "simulacra", "simulacrum", "smooth space", "spectacle",
    "striated space", "subaltern", "supplement", "trace", "transversality", "war machine"
]

terms = non_italicized_terms + italicized_terms

# Academic Vocabulary: Broad academic terms and jargon, not strictly specific to postmodernism
academic_vocab = [
    "activism", "advocacy", "agency", "agonism", "algorithmic culture", "algorithmic governance",
    "allyship", "artificial intelligence", "assemblage theory", "autopoiesis", "borderlands",
    "capitalism", "chaosmos", "coalition", "concept", "consumerism", "contact zone", "creolized",
    "critical race theory", "critical theory", "cultural studies", "cyberspace", "datafication",
    "deconstructionism", "difference", "dispositif", "disruption", "diversity", "ecosophy",
    "emancipation", "empowerment", "entanglement", "entrepreneurial self", "epistemological",
    "epistemology", "equity", "ethics", "event", "existential", "feminism", "flat ontology",
    "flow", "fold", "function", "gender studies", "geophilosophy", "global", "glocal",
    "healing", "hermeneutic", "hermeneutics", "historicity", "hybrid", "in-between",
    "inclusion", "interdisciplinarity", "intervention", "intra-action", "justice", "liberation",
    "liminal", "local", "majoritarian", "Marxism", "Marxist", "materiality", "media archaeology",
    "media studies", "mestiza", "minoritarian", "molar", "molecular", "movement",
    "multiplicity", "network", "new materialism", "nomadic", "ontological", "ontology",
    "paradigm", "participation", "percept", "phenomenological", "plane of consistency",
    "plane of immanence", "post-feminist", "post-structuralist", "postcolonial",
    "postcolonialism", "privacy", "psychoanalysis", "psychoanalytic", "reflexivity",
    "reiteration", "representation", "resistance", "sedentary", "semiotic", "semiotics",
    "singularity", "situated knowledge", "social justice", "software studies", "solidarity",
    "state apparatus", "strata", "structuralism", "structuralist", "subversion",
    "surveillance studies", "sympoiesis", "technology", "teleology", "third space",
    "threshold", "transcendence", "transhumanism", "transnational", "utopia",
    "virtual reality", "vibrant matter"
]

# Contexts (unchanged)
contexts = [
    "in the context of late capitalism",
    "within the framework of postmodernity",
    "through the lens of biopolitics",
    "against the backdrop of globalization",
    "in the age of digital surveillance",
    "amidst the ruins of neoliberalism",
    "under the shadow of postcolonial critique",
    "in the wake of deconstruction",
    "through the prism of queer theory",
    "in the era of climate crisis",
    "within the matrix of intersectionality",
    "against the grain of hegemonic discourse",
    "in the interstices of cultural hybridity",
    "through the gaze of the subaltern"
]

# Adjectives (unchanged)
adjectives = [
    "radical", "critical", "postmodern", "deconstructive", "philosophical",
    "ethical", "political", "economic", "social", "cultural", "gendered",
    "racial", "class-based", "discursive", "powerful", "knowledgeable",
    "existential", "real", "modern", "global", "technological", "artistic",
    "literary", "historical", "scientific", "just", "subjective", "hegemonic",
    "biopolitical", "postcolonial", "hybrid", "transnational", "digital",
    "intersectional", "decolonial", "queer", "feminist", "Marxist",
    "psychoanalytic", "semiotic", "hermeneutic", "phenomenological", "structuralist",
    "post-structuralist", "posthuman", "cyborg", "simulated", "hyperreal",
    "spectacular", "dromological", "nomadic", "rhizomatic", "assembled",
    "affective", "embodied", "situated", "performative", "discursive",
    "hegemonic", "counter-hegemonic", "subversive", "transgressive", "liminal",
    "hybrid", "creolized", "mestiza", "borderland", "diasporic",
    "transnational", "global", "local", "glocal", "cosmopolitan",
    "multicultural", "pluriversal", "epistemic", "ontological", "ethical"
]

# Philosopher Concepts: Cleaned, no asterisks
philosopher_concepts = {
    "Jean Baudrillard": ["simulacra", "hyperreality", "the desert of the real", "spectacle"],
    "Michel Foucault": ["power/knowledge", "discipline", "biopolitics", "genealogy", "governmentality", "panopticism"],
    "Jacques Derrida": ["deconstruction", "différance", "trace", "supplement", "aporia", "logocentrism"],
    "Gilles Deleuze": ["rhizome", "assemblage", "deterritorialization", "reterritorialization", "nomadism", "body without organs"],
    "Félix Guattari": ["rhizome", "assemblage", "deterritorialization", "reterritorialization", "schizoanalysis", "transversality"],
    "Judith Butler": ["gender performativity", "queer theory", "precarity", "subjectivity"],
    "Donna Haraway": ["cyborg", "posthumanism", "chthulucene", "ecocriticism"],
    "Fredric Jameson": ["late capitalism", "pastiche", "cognitive mapping", "postmodern sublime"],
    "Jean-François Lyotard": ["incredulity towards metanarratives", "metanarrative", "poststructuralism"],
    "Slavoj Žižek": ["ideology", "the gaze", "jouissance", "hegemony"],
    "Julia Kristeva": ["intertextuality", "abjection", "semiotics", "subjectivity"],
    "Linda Hutcheon": ["parody", "irony", "historiographic metafiction", "pastiche"],
    "Brian McHale": ["postmodern sublime", "fragmentation", "pluralism"],
    "Paul Virilio": ["dromology", "speed", "accelerationism", "surveillance capitalism"],
    "Homi K. Bhabha": ["hybridity", "mimicry", "diaspora", "transnationalism"],
    "Gayatri Chakravorty Spivak": ["subaltern", "decoloniality", "epistemic disobedience", "strategic essentialism"],
    "Edward Said": ["orientalism", "cultural imperialism", "postcolonialism", "discourse"],
    "Luce Irigaray": ["phallogocentrism", "phallocentrism", "the feminine", "binary opposition"],
    "Jacques Lacan": ["the gaze", "the Other", "jouissance", "mirror stage"],
    "Henri Lefebvre": ["the production of space", "everyday life", "urban revolution"],
    "Maurice Blanchot": ["the space of literature", "fragmentation", "immanence"],
    "Roland Barthes": ["intertextuality", "death of the author", "semiotics", "discourse"],
    "Richard Rorty": ["contingency", "irony", "pluralism"],
    "Stanley Fish": ["interpretive communities", "reader-response theory"],
    "Terry Eagleton": ["ideology", "hegemony", "literary theory", "cultural criticism"],
    "Brian Massumi": ["affect theory", "affect", "sensation"],
    "Mark Fisher": ["hauntology", "capitalist realism", "neoliberalism"],
    "Franco Berardi": ["semiocapitalism", "cognitive capitalism", "precarity"],
    "Nick Land": ["accelerationism", "hyperreality", "cyberculture"],
    "Manuel DeLanda": ["assemblage", "nonlinear history", "immanence"],
    "Rosi Braidotti": ["posthumanism", "nomadism", "becoming"],
    "Katherine Hayles": ["digital humanities", "posthumanism", "cybernetics"],
    "Jean-Luc Nancy": ["community", "being singular plural", "immanence"],
    "Giorgio Agamben": ["biopolitics", "state of exception", "bare life", "sovereignty"],
    "Alain Badiou": ["the event", "fidelity", "immanence"],
    "Bruno Latour": ["actor-network theory", "anthropocene", "ecocriticism"],
    "Isabelle Stengers": ["cosmopolitics", "ecology of practices", "pluriverse"],
    "Avital Ronell": ["technology", "addiction", "alterity"],
    "Catherine Malabou": ["plasticity", "trauma", "ontology of the accident"],
    "Quentin Meillassoux": ["speculative realism", "correlationism", "contingency"],
    "Ray Brassier": ["speculative realism", "nihilism", "transcendental nihilism"],
    "Graham Harman": ["object-oriented ontology", "speculative realism", "alterity"],
    "Elizabeth Grosz": ["becoming", "time", "the incorporeal"],
    "Achille Mbembe": ["necropolitics", "postcolony", "racial capitalism"],
    "Byung-Chul Han": ["burnout", "transparency society", "neoliberal subjectivity"],
    "Bernard Stiegler": ["technics", "disorientation", "epiphylogenesis"],
    "Lauren Berlant": ["affective labor", "cruel optimism", "intimate publics"],
    "Wang Hui": ["depoliticized politics", "China's new order", "modernity"],
    "Dipesh Chakrabarty": ["provincializing Europe", "the Anthropocene", "postcolonialism"],
    "Walter Mignolo": ["decoloniality", "border thinking", "epistemic disobedience"],
    "Sylvia Wynter": ["coloniality of power", "human being as praxis", "after man"],
    "Frantz Fanon": ["decolonization", "colonialism", "the wretched of the earth"],
    "Bell Hooks": ["intersectionality", "feminist theory", "cultural criticism"],
    "Cornel West": ["prophetic pragmatism", "race matters", "democracy"],
    "Angela Davis": ["abolition", "prison-industrial complex", "social justice"],
    "Audre Lorde": ["intersectionality", "self-care", "poetry as illumination"],
    "Sara Ahmed": ["queer phenomenology", "affect", "willful subjects"],
    "Gayle Rubin": ["sex/gender system", "traffic in women", "thinking sex"],
    "Eve Kosofsky Sedgwick": ["queer theory", "epistemology of the closet", "performativity"],
    "Michael Hardt": ["multitude", "empire", "immaterial labor"],
    "Antonio Negri": ["multitude", "empire", "constituent power"],
    "Étienne Balibar": ["citizenship", "equaliberty", "sovereignty"],
    "Ernesto Laclau": ["hegemony", "populism", "discourse"],
    "Chantal Mouffe": ["agonistic pluralism", "radical democracy", "hegemony"],
    "Nancy Fraser": ["redistribution", "recognition", "social reproduction theory"],
    "Axel Honneth": ["struggle for recognition", "freedom", "justice"],
    "Jürgen Habermas": ["communicative action", "public sphere", "discourse ethics"],
    "Kwame Anthony Appiah": ["cosmopolitanism", "ethics of identity", "cultural relativism"],
    "Martha Nussbaum": ["capabilities approach", "justice", "human capital"],
    "Amartya Sen": ["development as freedom", "capabilities approach", "justice"],
    "Arjun Appadurai": ["scapes", "globalization", "transnationalism"],
    "Stuart Hall": ["cultural studies", "encoding/decoding", "diaspora"],
    "Paul Gilroy": ["the black Atlantic", "double consciousness", "diaspora"],
    "Édouard Glissant": ["poetics of relation", "opacity", "archipelagic thinking"],
    "Ngũgĩ wa Thiong'o": ["decolonizing the mind", "global South", "language"],
    "Chinua Achebe": ["postcolonialism", "cultural imperialism", "things fall apart"],
    "Wole Soyinka": ["myth", "cultural relativism", "the burden of memory"],
    "Amin Maalouf": ["identity", "cultural relativism", "disordered world"],
    "Tariq Ali": ["clash of fundamentalisms", "counter-hegemony", "global South"],
    "Vandana Shiva": ["ecofeminism", "biopiracy", "earth democracy"],
    "Ashis Nandy": ["the intimate enemy", "tradition", "cultural relativism"],
    "Partha Chatterjee": ["nationalist thought", "the politics of the governed", "postcolonialism"],
    "Mahmood Mamdani": ["citizen and subject", "settler colonialism", "decolonization"],
    "Enrique Dussel": ["philosophy of liberation", "transmodernity", "decoloniality"],
    "Anibal Quijano": ["coloniality of power", "epistemic coloniality", "modernity/coloniality"],
    "Maria Lugones": ["coloniality of gender", "heterosexualism", "pilgrimages"],
    "Gloria Anzaldúa": ["borderlands", "mestiza consciousness", "nepantla"],
    "Chela Sandoval": ["methodology of the oppressed", "differential consciousness", "third space"],
    "Linda Tuhiwai Smith": ["decolonizing methodologies", "indigeneity", "mana wahine"],
    "Taiaiake Alfred": ["indigenous resurgence", "sovereignty", "land back"],
    "Leanne Betasamosake Simpson": ["indigenous freedom", "land back", "as we have always done"],
    "Vine Deloria Jr.": ["indigeneity", "sovereignty", "god is red"]
}

# Lists of first names
first_names = [
    "John", "Jane", "Michael", "Emily", "David", "Sarah", "Robert", "Laura",
    "James", "Maria", "William", "Olivia", "Emma", "Andrew", "Sophia",
    "Matthew", "Isabella", "Daniel", "Charlotte", "Joseph", "Amelia",
    "Ryan", "Mia", "Noah", "Ava", "Jacob", "Lily", "Ethan", "Chloe",
    "Alexander", "Grace", "Benjamin", "Zoey", "Nicholas", "Nora",
    "Samuel", "Scarlett", "Jonathan", "Aria", "Nathan", "Eva",
    "Tyler", "Riley", "Joshua", "Avery", "Brandon", "Sofia",
    "Henry", "Victoria", "Thomas", "Zoe", "Christopher", "Layla",
    "Anthony", "Mila", "Samuel", "Nora", "Oliver", "Harper",
    "Gabriel", "Evelyn", "Lucas", "Abigail", "Mason", "Emily",
    "Logan", "Madison", "Ethan", "Chloe", "Jackson", "Avery",
    "Aiden", "Sophie", "Caleb", "Isabelle", "Wyatt", "Lily",
    "Jayden", "Grace", "Nathan", "Scarlett", "Landon", "Hannah",
    "Grayson", "Zoe", "Owen", "Victoria", "Carter", "Natalie",
    "Dylan", "Brooklyn", "Julian", "Samantha", "Levi", "Audrey",
    "Isaac", "Savannah", "Eli", "Claire", "Max", "Alexa",
    "Liam", "Olivia", "Noah", "Emma", "William", "Ava",
    "James", "Sophia", "Benjamin", "Isabella", "Daniel", "Mia",
    "Matthew", "Charlotte", "Alexander", "Amelia", "Joseph", "Evelyn",
    "David", "Abigail", "Samuel", "Emily", "John", "Madison",
    "Kwame", "Amina", "Ngozi", "Tariq", "Fatima", "Akira", "Mei", "Rahul",
    "Priya", "Hiroshi", "Diego", "Sofia", "Juan", "Maria", "Pablo",
    "Ahmed", "Mohammad", "Layla", "Omar", "Yazzie", "Tsosie", "Crazy Horse",
    "Tecumseh", "Sitting Bull", "Malala", "Zainab", "Amir", "Leila", "Yusuf",
    "Saanvi", "Arjun", "Ananya", "Kabir", "Sakura", "Kenji", "Aisha", "Zara",
    "Rafael", "Lucia", "Mateo", "Camila", "Nguyen", "Tran", "Kim", "Lee",
    "Patel", "Kumar", "Singh", "Choi", "Park", "Li", "Wang", "Zhang",
    "Chen", "Liu", "Yang", "Huang", "Zhao", "Zhou", "Wu", "Xu", "Sun",
    "Ma", "Zhu", "Hu", "Guo", "He", "Gao", "Lin", "Luo", "Tang", "Yu",
    "Cao", "Fang", "Ren", "Liang", "Xie", "Song", "Zheng", "Han", "Zou",
    "Pan", "Jiang", "Wei", "Ding", "Chang", "Qian", "Shen", "Jin", "Qiu",
    "Lu", "Aaliyah", "Jamal", "Keisha", "Tyrone", "Lakisha", "Darnell",
    "Tanisha", "DeShawn", "Latoya", "Jermaine", "Ebony", "Malik", "Shaniqua",
    "Andre", "Kiara", "Jasmine", "Tremaine", "Imani", "Ebony", "Shaquille"
]

# Lists of last names
last_names = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson",
    "White", "Harris", "Martin", "Thompson", "Young", "Allen", "King",
    "Scott", "Green", "Baker", "Adams", "Nelson", "Mitchell", "Perez",
    "Robinson", "Hall", "Walker", "Ward", "Turner", "Watson", "Russell",
    "Stewart", "Morris", "Coleman", "Murphy", "Bailey", "Cook", "Howard",
    "Morgan", "Bell", "Thompson", "Sanders", "Price", "Richardson",
    "Cooper", "Reed", "Kelly", "Shaw", "Ortiz", "Jordan", "Long", "Foster",
    "Jimenez", "Torres", "Kennedy", "Powell", "Simmons", "Brooks", "Ramirez",
    "Flores", "Wood", "Washington", "Cole", "West", "Barnes", "Gray",
    "Henry", "Rose", "Rice", "Morgan", "Burke", "Harvey", "Dixon", "Mills",
    "Warner", "Terry", "Reed", "Bennett", "Rios", "Hart", "Ellis", "Fernandez",
    "Greene", "Mendoza", "Wagner", "Hudson", "Sanchez", "Medina", "Fox",
    "Hawkins", "Price", "Berry", "Montgomery", "Butler", "Daniels", "Fisher",
    "Vaughn", "Davidson", "Castillo", "Oliver", "Pena", "Hunter", "Cross",
    "Lawson", "Meyer", "Peters", "Spencer", "Palmer", "Wallace", "Duncan",
    "Fleming", "Oneill", "Webb", "Welch", "Ochoa", "Wilkins", "Barker",
    "Holt", "Huff", "Donovan", "Mcbride", "Blackburn", "Bowers", "Mccoy",
    "Mckay", "Raymond", "Robbins", "Rodriguez", "Thornton", "Valdez",
    "Wiggins", "Albert", "Castro", "Daugherty", "Hickman", "Hooper",
    "Kline", "Mccall", "Melendez", "Mullen", "Rodriguez", "Sampson",
    "Shepard", "Small", "Stokes", "Trujillo", "Waters", "Wilkerson",
    "Wise", "Woodard", "Patel", "Kumar", "Singh", "Choi", "Kim", "Lee",
    "Park", "Nguyen", "Tran", "Pham", "Li", "Wang", "Zhang", "Chen",
    "Liu", "Yang", "Huang", "Zhao", "Zhou", "Wu", "Xu", "Sun", "Ma",
    "Zhu", "Hu", "Guo", "He", "Gao", "Lin", "Luo", "Tang", "Yu", "Cao",
    "Fang", "Ren", "Liang", "Xie", "Song", "Zheng", "Han", "Zou", "Pan",
    "Jiang", "Wei", "Ding", "Chang", "Qian", "Shen", "Jin", "Qiu", "Lu",
    "Nkrumah", "Achebe", "Soyinka", "Tutu", "Diop", "Tagore", "Gandhi",
    "Confucius", "Lao", "Suzuki", "Paz", "Neruda", "Vargas Llosa", "Cortazar",
    "Allende", "Al-Ghazali", "Ibn Sina", "Rushdie", "Said", "Mernissi",
    "Crazy Horse", "Tecumseh", "Sitting Bull", "Malala", "Zainab", "Amir",
    "Leila", "Yusuf", "Saanvi", "Arjun", "Ananya", "Kabir", "Sakura",
    "Kenji", "Aisha", "Zara", "Rafael", "Lucia", "Mateo", "Camila",
    "Nguyen", "Tran", "Kim", "Lee", "Patel", "Kumar", "Singh", "Choi",
    "Park", "Li", "Wang", "Zhang", "Chen", "Liu", "Yang", "Huang", "Zhao",
    "Zhou", "Wu", "Xu", "Sun", "Ma", "Zhu", "Hu", "Guo", "He", "Gao",
    "Lin", "Luo", "Tang", "Yu", "Cao", "Fang", "Ren", "Liang", "Xie",
    "Song", "Zheng", "Han", "Zou", "Pan", "Jiang", "Wei", "Ding", "Chang",
    "Qian", "Shen", "Jin", "Qiu", "Lu", "Aaliyah", "Jamal"
]

# Lists of years
years = list(range(1950, 2025))

# Lists of publishers
publishers = [
   "Oxford University Press", "Cambridge University Press",
    "Harvard University Press", "Yale University Press",
    "Stanford University Press", "University of California Press",
    "University of Chicago Press", "Columbia University Press",
    "MIT Press", "Routledge", "Palgrave Macmillan", "Sage Publications",
    "Wiley-Blackwell", "Elsevier", "Taylor & Francis", "Bloomsbury Academic",
    "Duke University Press", "Cornell University Press", "Johns Hopkins University Press",
    "University of Minnesota Press", "University of Michigan Press",
    "University of Pennsylvania Press", "University of Texas Press",
    "University of Washington Press", "University of Wisconsin Press",
    "New York University Press", "University of Toronto Press",
    "McGill-Queen's University Press", "Edinburgh University Press",
    "Manchester University Press", "Ashgate Publishing", "Routledge-Cavendish",
    "Kluwer Academic Press", "Brill Academic Press", "Peter Lang Publishing",
    "Lexington Books", "Rowman & Littlefield", "Continuum International Publishing Group",
    "Zed Books", "Verso Books", "Pluto Press", "Haymarket Books",
    "Duke University Press Books", "University of Illinois Press",
    "University of Nebraska Press", "University of North Carolina Press",
    "University of Georgia Press", "Louisiana State University Press",
    "Mississippi University Press", "University of Alabama Press",
    "University of Florida Press", "University of Iowa Press",
    "University of Kansas Press", "University of New Mexico Press",
    "University of Oklahoma Press", "University of South Carolina Press",
    "University of Utah Press", "University of Arizona Press",
    "University of Colorado Press", "University of Idaho Press",
    "University of Nevada Press", "University of New Mexico Press",
    "University of Oregon Press", "University of Washington Press",
    "Springer", "Nature Publishing Group", "Wiley", "SAGE Journals",
    "APA Journals", "IEEE Xplore", "ACM Digital Library", "Emerald Insight",
    "Pambazuka Press", "University of KwaZulu-Natal Press", "Oxford University Press (India)",
    "Cambridge University Press (India)", "Beijing University Press", "Editorial Universidad de Buenos Aires",
    "Universidad Nacional Autónoma de México", "American University in Cairo Press", "Al-Qasimi Publications",
    "African Books Collective", "Asia Pacific Press", "Latin American Bureau", "Middle East Research and Information Project"
]

# Lists of title words
title_words = [
   "Exploring", "Analyzing", "Re-examining", "Deconstructing", "Interrogating",
    "Critiquing", "Reframing", "Revisiting", "Unpacking", "Problematizing",
    "Understanding", "Theorizing", "Mapping", "Tracing", "Excavating",
    "Investigating", "Examining", "Interpreting", "Reading", "Writing",
    "Rethinking", "Reimagining", "Reconceptualizing", "Reconfiguring", "Reassessing",
    "Challenging", "Contesting", "Disrupting", "Subverting", "Transgressing",
    "Resisting", "Liberating", "Emancipating", "Transforming", "Revolutionizing",
    "Decolonizing", "Queering", "Feminizing", "Globalizing", "Localizing",
    "Hybridizing", "Creolizing", "Mestizaje", "Bordering", "Crossing",
    "Bridging", "Connecting", "Linking", "Networking", "Assembling",
    "Entangling", "Interweaving", "Interfacing", "Interacting", "Intra-acting",
    "Diffracting", "Reflecting", "Refracting", "Mirroring", "Echoing",
    "Resonating", "Vibrating", "Pulsing", "Flowing", "Folding",
    "Unfolding", "Enfolding", "Infolding", "Outfolding", "Becoming",
    "Being", "Existing", "Living", "Dying", "Haunting",
    "Spectering", "Ghosting", "Shadowing", "Tracing", "Mapping",
    "Charting", "Navigating", "Orienting", "Disorienting", "Reorienting",
    "Positioning", "Situating", "Locating", "Dislocating", "Relocating",
    "Placing", "Displacing", "Replacing", "Spacing", "Timing",
    "Rhythming", "Syncing", "Desyncing", "Harmonizing", "Dissonating",
    "Attuning", "Detuning", "Resonating", "Vibrating", "Oscillating",
    "Pulsing", "Beating", "Breathing", "Living", "Dying",
    "Being", "Becoming", "Existing", "Persisting", "Enduring",
    "Surviving", "Thriving", "Flourishing", "Growing", "Shrinking",
    "Expanding", "Contracting", "Stretching", "Compressing", "Folding",
    "Unfolding", "Enfolding", "Infolding", "Outfolding", "Wrapping",
    "Unwrapping", "Enveloping", "Unenveloping", "Covering", "Uncovering",
    "Revealing", "Concealing", "Showing", "Hiding", "Displaying",
    "Obscuring", "Illuminating", "Darkening", "Lightening", "Shadowing",
    "Highlighting", "Emphasizing", "De-emphasizing", "Foregrounding", "Backgrounding",
    "Centering", "Decentered", "Marginalizing", "Peripheralizing", "Centralizing",
    "Focusing", "Defocusing", "Zooming", "Panning", "Tilting",
    "Rotating", "Spinning", "Turning", "Twisting", "Bending",
    "Straightening", "Curving", "Looping", "Circling", "Spiraling",
    "Winding", "Unwinding", "Coiling", "Uncoiling", "Knotting",
    "Unknotting", "Tying", "Untying", "Binding", "Unbinding",
    "Connecting", "Disconnecting", "Linking", "Unlinking", "Attaching",
    "Detaching", "Joining", "Separating", "Merging", "Splitting",
    "Combining", "Dividing", "Uniting", "Differentiating", "Integrating",
    "Disintegrating", "Assembling", "Disassembling", "Constructing", "Deconstructing",
    "Building", "Demolishing", "Erecting", "Dismantling", "Creating",
    "Destroying", "Generating", "Annihilating", "Producing", "Consuming",
    "Making", "Unmaking", "Forming", "Deforming", "Shaping",
    "Reshaping", "Molding", "Remolding", "Fashioning", "Refashioning",
    "Crafting", "Recrafting", "Designing", "Redesigning", "Planning",
    "Replanning", "Organizing", "Reorganizing", "Structuring", "Restructuring",
    "Ordering", "Reordering", "Arranging", "Rearranging", "Composing",
    "Decomposing", "Posing", "Reposing", "Positioning", "Repositioning",
    "Placing", "Displacing", "Replacing", "Misplacing", "Locating",
    "Relocating", "Dislocating", "Situating", "Resituating", "Contextualizing",
    "Decontextualizing", "Recontextualizing", "Framing", "Reframing", "Enframing",
    "Deframing", "Bounding", "Unbounding", "Limiting", "Unlimited",
    "Constraining", "Liberating", "Restricting", "Unrestricting", "Regulating",
    "Deregulating", "Governing", "Ungoverning", "Controlling", "Uncontrolling",
    "Managing", "Unmanaging", "Directing", "Misdirecting", "Guiding",
    "Misguiding", "Leading", "Misleading", "Following", "Unfollowing",
    "Tracking", "Untracking", "Tracing", "Erasing", "Marking",
    "Unmarking", "Signaling", "Unsignaling", "Indicating", "Unindicating",
    "Pointing", "Unpointing", "Showing", "Hiding", "Revealing",
    "Concealing", "Disclosing", "Enclosing", "Opening", "Closing",
    "Beginning", "Ending", "Starting", "Stopping", "Initiating",
    "Terminating", "Launching", "Landing", "Taking off", "Touching down",
    "Ascending", "Descending", "Rising", "Falling", "Climbing",
    "Descending", "Soaring", "Plummeting", "Levitating", "Sinking",
    "Floating", "Sinking", "Drifting", "Anchoring", "Mooring",
    "Unmooring", "Docking", "Undocking", "Berthing", "Unberthing",
    "Tethering", "Untethering", "Hitching", "Unhitching", "Fastening",
    "Unfastening", "Securing", "Unsecuring", "Locking", "Unlocking",
    "Sealing", "Unsealing", "Closing", "Opening", "Shutting",
    "Unshutting", "Barring", "Unbarring", "Blocking", "Unblocking",
    "Obstructing", "Unobstructing", "Impeding", "Unimpeding", "Hindering",
    "Unhindering", "Preventing", "Allowing", "Permitting", "Forbidding",
    "Enabling", "Disabling", "Facilitating", "Complicating", "Simplifying",
    "Clarifying", "Obfuscating", "Illuminating", "Darkening", "Enlightening",
    "Benighting", "Educating", "Miseducating", "Informing", "Misinforming",
    "Teaching", "Unteaching", "Learning", "Unlearning", "Knowing",
    "Unknowing", "Understanding", "Misunderstanding", "Comprehending", "Incomprehending",
    "Grasping", "Slipping", "Holding", "Releasing", "Gripping",
    "Letting go", "Seizing", "Relinquishing", "Capturing", "Freeing",
    "Imprisoning", "Liberating", "Enslaving", "Emancipating", "Oppressing",
    "Uplifting", "Burdening", "Unburdening", "Weighing down", "Lightening"
]

# Create concept clusters - groups of concepts that are semantically related
concept_clusters = {
    "power_discourse": ["power/knowledge", "discipline", "biopolitics", "governmentality", 
                       "sovereignty", "resistance", "hegemony", "control society"],
    "deconstruction_language": ["deconstruction", "différance", "trace", "supplement", 
                               "logocentrism", "phallogocentrism", "intertextuality"],
    "postmodernity": ["hyperreality", "simulacra", "spectacle", "pastiche", 
                     "incredulity towards metanarratives", "late capitalism"],
    "identity_politics": ["gender performativity", "intersectionality", "queer theory", 
                         "subaltern", "hybridity", "orientalism", "coloniality of power"],
    "materialism": ["rhizome", "assemblage", "body without organs", "deterritorialization", 
                   "nomadism", "smooth space", "striated space"],
    "critical_theory": ["dialectic", "cultural criticism", "Frankfurt School", 
                       "ideology", "utopia", "negative dialectics"],
    "affect_embodiment": ["affect theory", "emotion", "embodiment", "sense", 
                         "feeling", "intensities", "becoming"],
    "temporality": ["hauntology", "nostalgia", "futurism", "acceleration", 
                   "slow violence", "anthropocene", "capitalocene"]
}

# Create oppositional pairs - concepts that are often discussed in opposition
oppositional_pairs = [
    ("presence", "absence"),
    ("speech", "writing"),
    ("center", "margin"),
    ("identity", "difference"),
    ("subject", "object"),
    ("structure", "agency"),
    ("modernity", "postmodernity"),
    ("global", "local"),
    ("real", "virtual"),
    ("ideology", "utopia"),
    ("smooth space", "striated space"),
    ("deterritorialization", "reterritorialization"),
    ("molar", "molecular"),
    ("major", "minor"),
    ("control", "resistance"),
    ("hegemony", "counter-hegemony"),
    ("reason", "affect"),
    ("masculine", "feminine"),
    ("colonizer", "colonized"),
    ("self", "other")
]

# Create citation relationships - which philosophers tend to be cited together
citation_relationships = {
    "Derrida": ["Lacan", "Heidegger", "Levinas", "Saussure", "Nietzsche"],
    "Foucault": ["Nietzsche", "Canguilhem", "Bataille", "Marx", "Kant"],
    "Deleuze": ["Spinoza", "Nietzsche", "Bergson", "Guattari", "Simondon"],
    "Butler": ["Foucault", "Derrida", "Lacan", "Wittig", "Irigaray"],
    "Baudrillard": ["Marx", "Bataille", "Debord", "McLuhan", "Barthes"],
    "Spivak": ["Marx", "Derrida", "Gramsci", "Said", "Foucault"],
    "Žižek": ["Lacan", "Hegel", "Marx", "Badiou", "Butler"],
    "Haraway": ["Marx", "Foucault", "Harding", "Latour", "Butler"]
}

# Philosophical movements and their associated philosophers
philosophical_movements = {
    "deconstruction": ["Derrida", "Spivak", "Nancy", "Caputo", "Bennington"],
    "poststructuralism": ["Foucault", "Deleuze", "Guattari", "Kristeva", "Baudrillard", "Lyotard"],
    "critical_theory": ["Adorno", "Horkheimer", "Benjamin", "Marcuse", "Habermas"],
    "feminist_theory": ["Butler", "Irigaray", "Kristeva", "Haraway", "hooks", "Fraser"],
    "postcolonial_theory": ["Said", "Spivak", "Bhabha", "Mbembe", "Mignolo", "Quijano"],
    "queer_theory": ["Butler", "Sedgwick", "Halberstam", "Edelman", "Muñoz"],
    "new_materialism": ["Barad", "Bennett", "Braidotti", "Haraway", "Latour"],
    "accelerationism": ["Land", "Srnicek", "Williams", "Brassier", "Negarestani"]
}

# Rhetorical devices commonly used in postmodern writing
rhetorical_devices = [
    "aporia", "catachresis", "chiasmus", "ellipsis", "hyperbole",
    "irony", "metalepsis", "metonymy", "paradox", "parataxis",
    "parrhesia", "prosopopoeia", "syllepsis", "synecdoche"
]

# Discursive modes that characterize postmodern writing
discursive_modes = [
    "self-reflexivity", "intertextuality", "parataxis", "recursion",
    "fragmentation", "pastiche", "bricolage", "metafiction",
    "ontological plurality", "temporal distortion", "heteroglossia"
]

# NEW ADDITION: Key philosophical works with accurate publication years
philosopher_key_works = {
    # French poststructuralists and postmodernists
    "Jacques Derrida": [
        ("Of Grammatology", 1976), 
        ("Writing and Difference", 1978),
        ("Margins of Philosophy", 1982),
        ("Positions", 1981),
        ("Limited Inc", 1988),
        ("Specters of Marx", 1994),
        ("The Gift of Death", 1995),
        ("Archive Fever", 1996),
        ("The Politics of Friendship", 1997),
        ("The Animal That Therefore I Am", 2008)
    ],
    "Michel Foucault": [
        ("Madness and Civilization", 1965),
        ("The Order of Things", 1970),
        ("The Archaeology of Knowledge", 1972),
        ("Discipline and Punish", 1977),
        ("The History of Sexuality, Vol. 1", 1978),
        ("The History of Sexuality, Vol. 2", 1985),
        ("The History of Sexuality, Vol. 3", 1986),
        ("Power/Knowledge", 1980),
        ("The Birth of the Clinic", 1973),
        ("The Use of Pleasure", 1984)
    ],
    "Jean Baudrillard": [
        ("Simulacra and Simulation", 1981),
        ("The System of Objects", 1968),
        ("For a Critique of the Political Economy of the Sign", 1972),
        ("The Mirror of Production", 1975),
        ("Symbolic Exchange and Death", 1976),
        ("In the Shadow of the Silent Majorities", 1983),
        ("America", 1986),
        ("The Gulf War Did Not Take Place", 1991),
        ("The Consumer Society", 1970),
        ("The Spirit of Terrorism", 2002)
    ],
    "Gilles Deleuze": [
        ("Difference and Repetition", 1968),
        ("The Logic of Sense", 1969),
        ("Nietzsche and Philosophy", 1962),
        ("Bergsonism", 1966),
        ("Expressionism in Philosophy: Spinoza", 1968),
        ("Kafka: Toward a Minor Literature", 1975),
        ("Foucault", 1986),
        ("The Fold: Leibniz and the Baroque", 1988),
        ("Cinema 1: The Movement-Image", 1983),
        ("Cinema 2: The Time-Image", 1985)
    ],
    "Gilles Deleuze & Félix Guattari": [
        ("Anti-Oedipus", 1972),
        ("A Thousand Plateaus", 1980),
        ("What Is Philosophy?", 1991)
    ],
    "Jean-François Lyotard": [
        ("The Postmodern Condition", 1984),
        ("The Differend", 1983),
        ("Libidinal Economy", 1974),
        ("The Inhuman", 1988),
        ("Lessons on the Analytic of the Sublime", 1994),
        ("Discourse, Figure", 2011),
        ("Just Gaming", 1985),
        ("Heidegger and 'the Jews'", 1990),
        ("Postmodern Fables", 1997),
        ("The Confession of Augustine", 2000)
    ],
    "Julia Kristeva": [
        ("Revolution in Poetic Language", 1984),
        ("Powers of Horror", 1982),
        ("Tales of Love", 1987),
        ("Black Sun", 1989),
        ("Strangers to Ourselves", 1991),
        ("Nations without Nationalism", 1993),
        ("New Maladies of the Soul", 1995),
        ("The Sense and Non-Sense of Revolt", 2000),
        ("Intimate Revolt", 2002),
        ("The Severed Head", 2012)
    ],
    "Judith Butler": [
        ("Gender Trouble", 1990),
        ("Bodies That Matter", 1993),
        ("Excitable Speech", 1997),
        ("The Psychic Life of Power", 1997),
        ("Precarious Life", 2004),
        ("Undoing Gender", 2004),
        ("Giving an Account of Oneself", 2005),
        ("Frames of War", 2009),
        ("Notes Toward a Performative Theory of Assembly", 2015),
        ("The Force of Nonviolence", 2020)
    ],
    "Donna Haraway": [
        ("Primate Visions", 1989),
        ("Simians, Cyborgs, and Women", 1991),
        ("Modest_Witness@Second_Millennium", 1997),
        ("The Companion Species Manifesto", 2003),
        ("When Species Meet", 2008),
        ("Staying with the Trouble", 2016),
        ("Crystals, Fabrics, and Fields", 1976),
        ("The Haraway Reader", 2004),
        ("Manifestly Haraway", 2016),
        ("Making Kin Not Population", 2018)
    ],
    "Roland Barthes": [
        ("Writing Degree Zero", 1953),
        ("Mythologies", 1957),
        ("Elements of Semiology", 1964),
        ("The Fashion System", 1967),
        ("S/Z", 1970),
        ("The Pleasure of the Text", 1973),
        ("Roland Barthes by Roland Barthes", 1975),
        ("A Lover's Discourse", 1977),
        ("Image-Music-Text", 1977),
        ("Camera Lucida", 1980)
    ],
    "Richard Rorty": [
        ("Philosophy and the Mirror of Nature", 1979),
        ("Consequences of Pragmatism", 1982),
        ("Contingency, Irony, and Solidarity", 1989),
        ("Objectivity, Relativism, and Truth", 1991),
        ("Essays on Heidegger and Others", 1991),
        ("Truth and Progress", 1998),
        ("Achieving Our Country", 1998),
        ("Philosophy and Social Hope", 1999),
        ("Against Bosses, Against Oligarchies", 1999),
        ("Philosophy as Cultural Politics", 2007)
    ],
    "Giorgio Agamben": [
        ("Homo Sacer", 1998),
        ("State of Exception", 2005),
        ("The Open", 2004),
        ("The Kingdom and the Glory", 2011),
        ("The Highest Poverty", 2013),
        ("The Use of Bodies", 2016),
        ("Remnants of Auschwitz", 1999),
        ("Infancy and History", 1993),
        ("The Coming Community", 1993),
        ("Potentialities", 1999)
    ],
    "Slavoj Žižek": [
        ("The Sublime Object of Ideology", 1989),
        ("Looking Awry", 1991),
        ("Enjoy Your Symptom!", 1992),
        ("Tarrying with the Negative", 1993),
        ("The Metastases of Enjoyment", 1994),
        ("The Plague of Fantasies", 1997),
        ("The Ticklish Subject", 1999),
        ("Welcome to the Desert of the Real", 2002),
        ("The Puppet and the Dwarf", 2003),
        ("Violence", 2008)
    ],
    "Fredric Jameson": [
        ("Marxism and Form", 1971),
        ("The Prison-House of Language", 1972),
        ("The Political Unconscious", 1981),
        ("Postmodernism, or, The Cultural Logic of Late Capitalism", 1991),
        ("Signatures of the Visible", 1990),
        ("The Geopolitical Aesthetic", 1992),
        ("The Seeds of Time", 1994),
        ("The Cultural Turn", 1998),
        ("A Singular Modernity", 2002),
        ("Archaeologies of the Future", 2005)
    ],
    "Gayatri Chakravorty Spivak": [
        ("In Other Worlds", 1987),
        ("The Post-Colonial Critic", 1990),
        ("Outside in the Teaching Machine", 1993),
        ("A Critique of Postcolonial Reason", 1999),
        ("Death of a Discipline", 2003),
        ("Other Asias", 2008),
        ("An Aesthetic Education in the Era of Globalization", 2012),
        ("Readings", 2014),
        ("Can the Subaltern Speak?", 1988),
        ("Nationalism and the Imagination", 2010)
    ],
    "Edward Said": [
        ("Orientalism", 1978),
        ("The Question of Palestine", 1979),
        ("Covering Islam", 1981),
        ("The World, the Text, and the Critic", 1983),
        ("After the Last Sky", 1986),
        ("Culture and Imperialism", 1993),
        ("Representations of the Intellectual", 1994),
        ("Out of Place", 1999),
        ("Reflections on Exile", 2000),
        ("Humanism and Democratic Criticism", 2004)
    ],
    "Homi K. Bhabha": [
        ("The Location of Culture", 1994),
        ("Nation and Narration", 1990),
        ("The Right to Narrate", 2001),
        ("Our Neighbours, Ourselves", 2011),
        ("The New Humanities", 2013),
        ("In the Cave of Making", 2010),
        ("Democracy De-realized", 2003),
        ("Cosmopolitanisms", 2001),
        ("Aura and Agora", 2001),
        ("The Black Savant and the Dark Princess", 1998)
    ],
    "Linda Hutcheon": [
        ("Narcissistic Narrative", 1980),
        ("A Theory of Parody", 1985),
        ("A Poetics of Postmodernism", 1988),
        ("The Politics of Postmodernism", 1989),
        ("Irony's Edge", 1994),
        ("Opera: Desire, Disease, Death", 1996),
        ("Bodily Charm", 2000),
        ("A Theory of Adaptation", 2006),
        ("The Canadian Postmodern", 2012),
        ("Rethinking Literary History", 2002)
    ],
    "Paul Virilio": [
        ("Speed and Politics", 1977),
        ("War and Cinema", 1989),
        ("The Aesthetics of Disappearance", 1991),
        ("The Art of the Motor", 1995),
        ("Open Sky", 1997),
        ("Politics of the Very Worst", 1999),
        ("The Information Bomb", 2000),
        ("Ground Zero", 2002),
        ("City of Panic", 2005),
        ("The University of Disaster", 2010)
    ],
    "Bell Hooks": [
        ("Ain't I a Woman", 1981),
        ("Feminist Theory: From Margin to Center", 1984),
        ("Talking Back", 1989),
        ("Yearning: Race, Gender, and Cultural Politics", 1990),
        ("Black Looks: Race and Representation", 1992),
        ("Teaching to Transgress", 1994),
        ("Outlaw Culture", 1994),
        ("Art on My Mind", 1995),
        ("Killing Rage", 1995),
        ("All About Love", 2000)
    ],
    "Michael Hardt & Antonio Negri": [
        ("Empire", 2000),
        ("Multitude", 2004),
        ("Commonwealth", 2009),
        ("Declaration", 2012),
        ("Assembly", 2017)
    ],
    "Alain Badiou": [
        ("Theory of the Subject", 1982),
        ("Being and Event", 1988),
        ("Ethics", 1993),
        ("Metapolitics", 1998),
        ("Logics of Worlds", 2006),
        ("The Communist Hypothesis", 2010),
        ("The Century", 2005),
        ("In Praise of Love", 2009),
        ("Philosophy for Militants", 2012),
        ("Mathematics of the Transcendental", 2014)
    ],
    "Luce Irigaray": [
        ("Speculum of the Other Woman", 1974),
        ("This Sex Which Is Not One", 1977),
        ("Marine Lover of Friedrich Nietzsche", 1980),
        ("An Ethics of Sexual Difference", 1984),
        ("Sexes and Genealogies", 1987),
        ("Je, Tu, Nous", 1990),
        ("I Love to You", 1996),
        ("Between East and West", 1999),
        ("The Way of Love", 2002),
        ("Sharing the World", 2008)
    ],
    "Jacques Lacan": [
        ("Écrits", 1966),
        ("The Four Fundamental Concepts of Psychoanalysis", 1973),
        ("The Ethics of Psychoanalysis", 1986),
        ("The Other Side of Psychoanalysis", 2007),
        ("On Feminine Sexuality", 1975),
        ("The Sinthome", 2005),
        ("My Teaching", 2005),
        ("The Triumph of Religion", 2013),
        ("Anxiety", 2014),
        ("The Formations of the Unconscious", 2017)
    ],
    "Bruno Latour": [
        ("Laboratory Life", 1979),
        ("Science in Action", 1987),
        ("We Have Never Been Modern", 1991),
        ("The Pasteurization of France", 1988),
        ("Aramis, or the Love of Technology", 1992),
        ("Politics of Nature", 1999),
        ("Reassembling the Social", 2005),
        ("On the Modern Cult of the Factish Gods", 2009),
        ("An Inquiry into Modes of Existence", 2013),
        ("Facing Gaia", 2017)
    ],
    "Nancy Fraser": [
        ("Unruly Practices", 1989),
        ("Justice Interruptus", 1997),
        ("Redistribution or Recognition?", 2003),
        ("Scales of Justice", 2008),
        ("Fortunes of Feminism", 2013),
        ("Capitalism: A Conversation in Critical Theory", 2018),
        ("The Old Is Dying and the New Cannot Be Born", 2019),
        ("Feminism for the 99%", 2019),
        ("Cannibal Capitalism", 2022)
    ],
    "Stuart Hall": [
        ("Policing the Crisis", 1978),
        ("The Hard Road to Renewal", 1988),
        ("Cultural Studies 1983", 2016),
        ("Familiar Stranger", 2017),
        ("Selected Political Writings", 2017),
        ("Essential Essays, Volume 1", 2018),
        ("Essential Essays, Volume 2", 2018),
        ("Cultural Studies", 1992)
    ]
}

# Additional academic journals beyond what's already in publishers list
academic_journals = [
    "Critical Inquiry", "Cultural Studies", "Theory, Culture & Society", 
    "Postmodern Culture", "Social Text", "New Literary History", "boundary 2", 
    "Public Culture", "Differences", "October", "Signs", "Cultural Critique",
    "Philosophy Today", "Continental Philosophy Review", "Philosophy & Social Criticism",
    "Hypatia", "Radical Philosophy", "The Journal of Speculative Philosophy",
    "PMLA", "Representations", "Modern Language Notes", "Contemporary Literature", 
    "Diacritics", "Grey Room", "Angelaki", "Parallax", "Substance", "positions", 
    "GLQ", "Interventions", "New Formations", "Transition", "Political Theory", 
    "Constellations", "Theory & Event", "Contemporary Political Theory", "Telos", 
    "Thesis Eleven", "Politics and Society", "Millennium"
]

# Title templates for generating plausible work titles
bibliography_title_templates = [
    # Single concept focus
    "On {concept}", 
    "Towards a Theory of {concept}",
    "Rethinking {concept}",
    "{concept} and Its Discontents",
    "The Question of {concept}",
    "{concept} Otherwise",
    "{concept} Reconsidered",
    "After {concept}",
    "{concept} and the Politics of Difference",
    "Reading {concept}",
    
    # Dual concept relations
    "{concept} and {concept2}",
    "Between {concept} and {concept2}",
    "{concept} as {concept2}",
    "From {concept} to {concept2}",
    "{concept} Against {concept2}",
    "{concept} Beyond {concept2}",
    "The {concept} of {concept2}",
    "{concept} in the Age of {concept2}",
    
    # Theoretical frameworks
    "The Dialectics of {concept}",
    "A Genealogy of {concept}",
    "The Archaeology of {concept}",
    "{concept}: A Critical Theory",
    "The Rhetoric of {concept}",
    "The Phenomenology of {concept}",
    "{concept} and Critical Practice",
    "Deconstructing {concept}",
    
    # Structural forms
    "Essays on {concept}",
    "{concept}: Selected Writings",
    "Fragments of {concept}",
    "Notes on {concept}",
    "{adj} Reflections on {concept}",
    "{concept}: Collected Essays",
    "The {concept} Reader",
    
    # Spatial/temporal framings
    "{concept} at the Margins",
    "{concept} in Transition",
    "Mapping {concept}",
    "The Time of {concept}",
    "Spaces of {concept}",
    "{concept} and Its Futures",
    "{concept} in Crisis",
    
    # Epistemological approach
    "Thinking {concept}",
    "Knowing {concept}",
    "The Limits of {concept}",
    "{concept} as Method",
    "The Ethics of {concept}",
    "The Politics of {concept}",
    "The Aesthetics of {concept}",
    
    # Provocative formats
    "Against {concept}",
    "{concept} Interrupted",
    "The End of {concept}",
    "{concept} and Its Others",
    "Unthinking {concept}",
    "The Illusion of {concept}",
    "{concept} as Ideology"
]